#!/usr/bin/env node
/**
 * generate_index.mjs — rebuilds brain/INDEX.md from the notes on disk.
 *
 * Deterministic execution-layer script (DOE): same input, same output.
 * The AI calls this after adding notes; it never hand-edits INDEX.md structure.
 *
 * Usage: node execution/generate_index.mjs   (run from the second-brain/ root)
 *
 * For each note it takes the first markdown heading as the summary line,
 * falling back to the first non-empty line, truncated to 100 chars.
 */

import { readdir, readFile, writeFile } from "node:fs/promises"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const vaultRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const brainDir = join(vaultRoot, "brain")
const categories = ["decisions", "notes", "references", "metrics", "ideas"]

async function summarize(filePath) {
  const raw = await readFile(filePath, "utf8")
  const lines = raw.split("\n")
  const heading = lines.find((l) => l.startsWith("# "))
  const firstLine = lines.find((l) => l.trim().length > 0 && !l.startsWith("#") && !l.startsWith(">"))
  const summary = (heading ? heading.replace(/^#\s*/, "") : (firstLine ?? "")).trim()
  return summary.length > 100 ? summary.slice(0, 97) + "..." : summary
}

async function main() {
  const sections = []
  let total = 0

  for (const cat of categories) {
    const dir = join(brainDir, cat)
    let files = []
    try {
      files = (await readdir(dir)).filter((f) => f.endsWith(".md")).sort().reverse() // newest first by date-prefixed filename
    } catch {
      // category folder missing — report and continue
      sections.push(`## ${cat}/\n\n_(folder missing)_`)
      continue
    }

    const lines = []
    for (const f of files) {
      const summary = await summarize(join(dir, f))
      lines.push(`- [[${f.replace(/\.md$/, "")}]] — ${summary}`)
      total++
    }
    sections.push(`## ${cat}/\n\n${lines.length ? lines.join("\n") : "_(empty)_"}`)
  }

  const out = [
    "# Brain Index",
    "",
    "> One line per note — the master map. The AI reads this first, then opens only what is relevant.",
    `> Auto-generated by \`execution/generate_index.mjs\`. Do not hand-edit; re-run the script instead.`,
    `> Last generated: ${new Date().toISOString().slice(0, 10)} · ${total} notes`,
    "",
    sections.join("\n\n"),
    "",
  ].join("\n")

  await writeFile(join(brainDir, "INDEX.md"), out, "utf8")
  console.log(`INDEX.md regenerated: ${total} notes across ${categories.length} categories`)
}

main().catch((err) => {
  console.error("generate_index failed:", err.message)
  process.exit(1)
})
